config:
  do_not_delete_cf: "true"
  slack:
    webhook: ((slack-webhook))
  github:
    access-token: ((github-access-token))
    private-key: ((github-private-key))
  cert-manager:
    enable: true
  cluster:
    name: ((world-name))
    worker-count: ((worker_count))
    admin-password: ((cluster-admin-password))
    uaa-admin-client-secret: ((uaa-admin-client-secret))
    nats-password: ((nats-password))
    windows-pool: false
  gcp:
    service-account-json: ((gcp-service-account-json))
    region: ((gcp-region))
    zone: ((gcp-zone))
    project-id: ((gcp-project-id))
    dns-service-account-json: ((gcp-dns-service-account-json))
  ibmcloud:
    account: ((ibmcloud-account))
    user: ((ibmcloud-user))
    password: ((ibmcloud-password))
  eirini:
    repo-key: ((eirini-repo-key))
  eirini-ci:
    branch: ((ci-resources-branch))
  eirini-release:
    branch: ((eirini-release-branch))
    repo-key: ((eirini-release-repo-key))
  dockerhub:
    user: ((dockerhub-user))
    password: ((dockerhub-password))
