---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: ci-resources
- name: eirini-release
- name: state

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  COMPONENT:
  CLUSTER_NAME:
  HELM_CHART:

run:
  path: ci-resources/tasks/helm-install/task.sh
