---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

params:
  FORK_BRANCH: eirini
  UPSTREAM: ../cc-ng
  UPSTREAM_BRANCH: master

inputs:
- name: ci-resources
- name: cc-ng-fork
- name: cc-ng

outputs:
- name: rebased-cc

run:
  path: ci-resources/tasks/rebase-cc/task.sh
